apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "nextjs-app.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.route.gatewayName }}
      namespace: {{ .Values.route.namespace | default "kube-system" }}
  hostnames:
    - {{ .Values.route.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.route.path | default "/" | quote }}
      backendRefs:
        - name: {{ include "nextjs-app.fullname" . }}
          port: {{ .Values.service.port }}
