{{- if .Values.rbac.logReader.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nextjs-app.fullname" . }}-log-reader
  namespace: {{ .Values.rbac.logReader.namespace | default (.Values.namespace | default "default") }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nextjs-app.fullname" . }}-log-reader
  namespace: {{ .Values.rbac.logReader.namespace | default (.Values.namespace | default "default") }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nextjs-app.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nextjs-app.fullname" . }}-log-reader
{{- end }}
