{{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nextjs-app.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
